In [4]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df = pd.read_csv("main_data.csv")

In [3]:
df.head()

director_name     actor_1_name      actor_2_name          actor_3_name  \
0      James Cameron      CCH Pounder  Joel David Moore             Wes Studi   
1     Gore Verbinski      Johnny Depp     Orlando Bloom        Jack Davenport   
2         Sam Mendes  Christoph Waltz      Rory Kinnear      Stephanie Sigman   
3  Christopher Nolan        Tom Hardy    Christian Bale  Joseph Gordon-Levitt   
4        Doug Walker      Doug Walker        Rob Walker               unknown   

                            genres  \
0  Action Adventure Fantasy Sci-Fi   
1         Action Adventure Fantasy   
2        Action Adventure Thriller   
3                  Action Thriller   
4                      Documentary   

                                         movie_title  \
0                                             avatar   
1           pirates of the caribbean: at world's end   
2                                            spectre   
3                              the dark knight rises   
4  star wars: episode vii - the force awakens    ...   

                                                comb  
0  CCH Pounder Joel David Moore Wes Studi James C...  
1  Johnny Depp Orlando Bloom Jack Davenport Gore ...  
2  Christoph Waltz Rory Kinnear Stephanie Sigman ...  
3  Tom Hardy Christian Bale Joseph Gordon-Levitt ...  
4  Doug Walker Rob Walker unknown Doug Walker Doc...

In [6]:
cv = CountVectorizer()
count_matrix = cv.fit_transform(df["comb"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [17]:
cosine_sim = cosine_similarity(count_matrix)
print(cosine_sim)

[[1.         0.24174689 0.16116459 ... 0.         0.         0.        ]
 [0.24174689 1.         0.18181818 ... 0.         0.         0.        ]
 [0.16116459 0.18181818 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.10540926 0.1       ]
 [0.         0.         0.         ... 0.10540926 1.         0.10540926]
 [0.         0.         0.         ... 0.1        0.10540926 1.        ]]


In [12]:
movie_user_likes = "avatar"
def get_index_from_title(title):
    return df[df.movie_title == title].index[0]
movie_index = get_index_from_title(movie_user_likes)

In [13]:
similar_movies = list(enumerate(cosine_sim[movie_index]))

In [14]:
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

In [16]:
def get_title_from_index(index):
    return df[df.index == index]["movie_title"].values[0]
i=0
for movie in sorted_similar_movies:
    print(get_title_from_index(movie[0]))
    i=i+1
    if i>15:
        break

avatar
aliens
mystery men
deep rising
dragonball: evolution
terminator 2: judgment day
the terminator
blade: trinity
star wars: the clone wars            
the amazing spider-man 2
2012
guardians of the galaxy
dune
wing commander
robocop 3
tron: legacy
